### ISSUE TITLE
pls add a better embed for pixiv

### ISSUE THREAD

**Issue by EggY0lk** [medjedqt/kiyobot#16]
**Brief explanation of the feature**
A better embed for pixiv, like how it is done for reddit post.

**Reasons as to why it should be implemented**
Pixiv embed only displays picture partially.

**Example of feature**
![image](https://user-images.githubusercontent.com/27946481/106248765-66671400-624c-11eb-87f7-9d0f27b05cdd.png)

**Additional Information of feature**
Pixiv: https://www.pixiv.net/en/

How it is currently displayed:
![image](https://user-images.githubusercontent.com/27946481/106248890-99a9a300-624c-11eb-9b86-26c9612280e4.png)

Pixiv API on pypi: https://pypi.org/project/pixiv-api/
Another Pixiv API I found: https://github.com/upbit/pixivpy

**Comment by medjedqt** [comment]
Main hurdle right now is Pixiv blocks hotlinking images and the only way to get the images is to download them which makes them not embeddable

**Comment by medjedqt** [comment]
discord.py does actually have a way to handle this but it is pretty much unstable

**Comment by EggY0lk** [comment]
> discord.py does actually have a way to handle this but it is pretty much unstable

so what did u do? I woke up and it works
