### ISSUE TITLE
pls add national eboy — Today at 09:35 say "make clone post files hurddur"

### ISSUE THREAD

**Issue by EggY0lk** [medjedqt/kiyobot#20]
**Brief explanation of the feature**
the command ?clone post files as well

**Reasons as to why it should be implemented**
to make shit easier

**Example of feature**
![image](https://user-images.githubusercontent.com/27946481/122317294-e23dd080-cf4f-11eb-8190-6a2caae2543c.png)

**Additional Information of feature**
none

**Comment by medjedqt** [comment]
done poggers
