### ISSUE TITLE
Remove Kiyohime

### ISSUE THREAD

**Issue by Vindicta** [medjedqt/kiyobot#9]

**Comment by medjedqt** [comment]
Dear Ms. Vindicta,

Thank you for your order to Remove Kiyohime. Your order will be laid out in seven (7) working days and will be done in exactly eight (8) working days from now.

Before then, we would like to know if you want to include a donation for your beloved developers as well as subscribe to our patreon. You may choose either and it is very much welcomed.

Our kiyobot is made to offer best results at very low cost. We are sure you will be very happy with this hellspawn.

Thanks again for your order. We look forward to receiving your further instruction to obliterate our so products.

Sincerely,

Ayo Oyedotun

Head of Operations

PeePee Holdings
